### ISSUE TITLE
Merge Halyard Export and Parallel Export tools + more features

### ISSUE THREAD

**Issue by asotona** [Merck/Halyard#22]
Halyard Export and Parallel Export should be unified under one tool with several options of execution.
Expected behaviour:
- number of mappers affects execution mode
- optional switch "local" can execute export locally (similar to current export - without YARN)
- halyard:parallelSplitBy should be mandatory only for >1 mappers non-local execution

**Comment by pulquero** [comment]
Same for Update, and can Update support halyard:parallelSplitBy too.

**Comment by asotona** [comment]
This issue become obsolete after the change from #46
