### ISSUE TITLE
RDF4J Workbench displaying zero 'repository size'

### ISSUE THREAD

**Issue by peterjohnlawrence** [Merck/Halyard#28]
Halyard repository, although it can be confirm that it contains statements via SPARQL queries etc, displays 0 number of statements and 0 number of labelled contexts
![image](https://user-images.githubusercontent.com/1612464/31774109-b1049b84-b4dc-11e7-99bf-cdba867ac16a.png)

**Comment by asotona** [comment]
Yes, Halyard repository is designed for large datasets and parallel computation. Several implementation attempts to count or estimate number of statements in real time failed. 
Correct numbers and even more statistics about the dataset are available using Halyard Stats tool https://merck.github.io/Halyard/tools.html#halyard-stats

**Comment by asotona** [comment]
I'll add a small workaround to try to count the number of all statements in case the stats are not calculated. However it will work for small datasets only due to a very short timeout.
