### ISSUE TITLE
SPARQL query with property path causing performance problems

### ISSUE THREAD

**Issue by peterjohnlawrence** [Merck/Halyard#29]
I have a TEST repository based on an RDF4J memory repository, and a Halyard repository, both with the same data(~35K statements) and contexts (2).
Most queries tested so far perform well but ones containing property paths present an issue:

>SELECT *
>WHERE { 
  > VALUES(?propertyType){(owl:DatatypeProperty)(owl:AnnotationProperty)(rdf:Property)} 
   >?property a ?propertyType  . 
   >?property rdfs:subPropertyOf* ?sproperty 
>}

In the memory repository this returns promptly, but Halyard times out (180 seconds)

Tested with and without the VALUES, and find the same issue, in other words this exhibits the same problem:

>SELECT *
>WHERE { 
 > ?property a owl:DatatypeProperty . 
  > ?property rdfs:subPropertyOf* ?sproperty 
>}

where it is known that there will be values for ?property.

The memory repository which contains the same sample data returns about 140 results, so there is not a large result set.

**Comment by peterjohnlawrence** [comment]
Update: The performance issue is only present if the Halyard repository is configured using Use Halyard Push Evaluation Strategy - true. Setting to false and the property path query issue disappears.

**Comment by asotona** [comment]
Thanks for the report, with the exact query I can debug the root cause.

**Comment by asotona** [comment]
I've performed deep testing of arbitrary length paths and zero length paths with various scenarios (including long chains, short and long cycles) and found no problems in the evaluation strategy.

Could you, please, attach an example of the graph data causing the problem?

Thanks,
Adam

**Comment by peterjohnlawrence** [comment]
I am afraid I can reproduce the query issues with the setup as follows:

- I used an existing RDF4J/Halyard that is being setup for a startups LDP project. It already has several Halyard repositories.
- I configured two Halyard repositories, one with 'push' enabled and the other without.
- I loaded northwind.model.v2.rdf and northwind.data.v1.rdf triple files using the RDF4J-workbench 'add' to load the files. (sent by email)
- There is a total of 34056 triples in each.

If I run the query

```
SELECT *
WHERE {
VALUES(?propertyType){(owl:DatatypeProperty)(owl:AnnotationProperty)(rdf:Property)}
?property a ?propertyType .
?property rdfs:subPropertyOf* ?sproperty
}
```

I get almost immediate response from the repository without the Push set, whilst the other repository fails to return any results before it times ou

**Comment by peterjohnlawrence** [comment]
The plot thickens.

- I created another Halyard instance, this time using the docker image: https://hub.docker.com/r/dicegroup/halyard/. This builds a one node local setup.
- I created two repositories, one with Push enabled
- I repeated the test of loading northwind.model.v2.rdf and northwind.data.v1.rdf triple files using the RDF4J-workbench 'add' to load the files to each repository.
- Now if I execute this query

```
SELECT *
WHERE {
?property a owl:DatatypeProperty .
?property rdfs:subPropertyOf* ?sproperty
}
```

There is ***no*** discernible difference in performance.

I can only think that there is some difference in how the HBase's are setup between the various test cases:

1. In the original case that I reported, I built a standalone HBase running on a local VirtualBox Ubuntu VM
2. In the second case I used a standalone Hbase built by a thirdparty following your instructions
3. In the third case (without performance issues) I used the docker image

What can we provide you to help diagnose the issue?

**Comment by asotona** [comment]
Thanks to your data I've been able to reproduce it and get full thread dump of the locked state.
Now I'm closer to the fix.

Thanks,
Adam

**Comment by asotona** [comment]
It seems that ArbitraryLengthPath evaluation is using synthetic child QueryModelNodes that are referencing to the ArbitraryLengthPath as to the parent node, however they are not regularly visited by QueryModelVisitor. This violation of the visitors pattern standard results in invalid priority calculation  in the HalyardStatementPatterEvaluation and wrong priority may cause thread exhaustion as seen in the thread dump of this issue.

I'll try a simple fix by assigning parent node priority to such direct synthetic nodes.

**Comment by asotona** [comment]
I'm unable to reproduce it after the patch, so it seems to be fixed :)
