### ISSUE TITLE
Missing class exception when using tomcat9/rdf4j/workbench 

### ISSUE THREAD

**Issue by peterjohnlawrence** [Merck/Halyard#30]
I wanted to use rdf4j/workbench but was getting a class exception. 
Solved this by adding "/home/hduser/hbase-1.2.6/lib/*.jar" to common.loader in catalina.properties. 
Not sure if this was your intention, or if it is something I had done with the install, but it seems to solve the problem

**Comment by asotona** [comment]
This is tutorial how to setup Tomcat: https://merck.github.io/Halyard/tools.html#rdf4j-web-applications
working `hadoop classpath` and `hbase classpath` commands are mandatory pre-conditions for Halyard. Manual addition of hbase jar files may not be enough - as HBase is not correctly configured.
