### ISSUE TITLE
Separate namespace prefix definitions in a system named graph

### ISSUE THREAD

**Issue by jindrichmynarz** [Merck/Halyard#37]
Halyard stores namespace prefixes in the default graph, in this form:

```ttl
@prefix halyard: <http://merck.github.io/Halyard/ns#> .

<http://www.w3.org/ns/sparql-service-description#> halyard:namespacePrefix "sd" .
```

These additional triples with the prefix declarations are stored in the default graph; hence mixed with the data loaded by the users. Consequently, it can skew the results of SPARQL queries over the default graph (e.g., `SELECT (COUNT(*) AS ?count) WHERE { [] ?p [] . }`).

It may be useful to separate the prefix declarations from the data loaded by users. For example, they can be stored in a "system" named graph (e.g., `halyard:system`). However, a downside of this solution is that a regular named graph can be modified by users, so a better isolation might be needed.

**Comment by asotona** [comment]
I think that proposed halyard:system is good solution. I don't see namespaces exposed to user as a problem.
