### ISSUE TITLE
Unify halyard:parallelSplitBy and halyard:decimateBy

### ISSUE THREAD

**Issue by jindrichmynarz** [Merck/Halyard#46]
Users may find it confusing when to use [`halyard:parallelSplitBy`](http://merck.github.io/Halyard/ns#parallelSplitBy) and [`halyard:decimateBy`](http://merck.github.io/Halyard/ns#decimateBy). It might be better to unify them to a single extension function that accepts a variable and a number of tasks to execute in parallel. Halyard Parallel Export now accepts this via `mapreduce.job.maps` Java property, while in Halyard Bulk Update and Halyard Bulk Export it is provided as an argument to `halyard:decimateBy`. Providing it as a function argument is more generic and suits both use cases.

**Comment by asotona** [comment]
Yes, halyard:parallelSplitBy and halyard:decimateBy usage is confusing and combination of Halyard Parallel Export, Bulk Export, Update and Bulk Update does not make it better.
I'm going to introduce new single function that will cover all cases.
halyard:forkAndFilterBy(<num_of_forks>, ?var1 [,?varN...]) should be enough to instruct Parallel Export, Bulk Export, and Bulk Update with the right number of parallel mappers to run (in the preparation stage) and do all the filtering (in runtime).
Halyard Parallel Export will loose the option defining the mappers.
Halyard Bulk Export will use single query for multiple parallel mappers.
And Halyard Bulk Update as well, plus it will allow to flexibly "forkAndFilterBy" in multi-stage SPARQL Updates.

**Comment by asotona** [comment]
Halyard Parallel Export can now be removed as all its functionality is now included in Halyard Bulk Export
