### ISSUE TITLE
create.xsl does not include all of the available repository types

### ISSUE THREAD

**Issue by peterjohnlawrence** [Merck/Halyard#48]
It looks like the transformations folder includes all create-<repositorytype>.xsl files, include create-hbase.xsl, but the corresponding create.xsl only shows a sub-selection in the drop-list.

I *think* the attached create.xsl (with additional .txt to satisfy Github)  is correct, in that it includes all variants available.
[create.xsl.txt](https://github.com/Merck/Halyard/files/2382796/create.xsl.txt)

**Comment by asotona** [comment]
Yes, create.xsl must be updated, ideally patched from the original during each build.
