### ISSUE TITLE
Option to specify alternate halyard-defaults.xml on cli

### ISSUE THREAD

**Issue by pulquero** [Merck/Halyard#52]
It would be nice to have a command line argument so that an alternate halyard-defaults.xml could be specified, something like:
halyard bulkupdate -config my-config.xml .....
I have found the settings for a load can be quite different to say a bulkupdate.

**Comment by asotona** [comment]
Halyard already supports generic Hadoop command line options, as described in: 
https://merck.github.io/Halyard/tools.html#halyard

Please test if following command works for you:
halyard bulkupdate -conf my-config.xml
