### ISSUE TITLE
Variables bound by BIND are unbound in FILTER

### ISSUE THREAD

**Issue by jindrichmynarz** [Merck/Halyard#69]
Variables bound by `BIND` are unbound in `FILTER` used within the same group. The following query produces empty results:

```rq
SELECT ?x
WHERE {
  BIND ("x" AS ?x)
  FILTER (?x = "x")
}
```

When `BIND` is wrapped in a sub-query, the FILTER works:

```rq
SELECT ?x
WHERE {
  {
    SELECT ?x
    WHERE {
	  BIND ("x" AS ?x)
    }
  }
  FILTER (?x = "x")
}
```

Both Jena and RDF4J in-memory store allow filtering on created via BIND.

**Comment by asotona** [comment]
Right, there is a bug in HalyardFilterOptimizer, which is too aggressive.
