### ISSUE TITLE
Inconsistent naming of source table in Halyard Tools

### ISSUE THREAD

**Issue by jindrichmynarz** [Merck/Halyard#73]
[Halyard Tools](https://merck.github.io/Halyard/tools.html) use different argument names for source tables.

* `--source` is used by PreSplit, Bulk Load
* `--source-dataset` is used by Stats, ElasticSearch Index, Update, Bulk Update, Export, Bulk Export, Profile
* `--target-dataset` is used by Bulk Delete

It would be useful to make the argument names consistent.

**Comment by asotona** [comment]
PreSplit and BulkLoad --source option does not represent dataset, it is "Source path(s) with RDF files, more paths can be delimited by comma, the paths are searched for the supported files recurrently"
While Stats,  ElasticSearch Index, Update, Bulk Update, Export, Bulk Export and Profile uses dataset as a source.

**Comment by jindrichmynarz** [comment]
You're right. The only inconsistency is in [Halyard Bulk Delete](https://merck.github.io/Halyard/tools.html#halyard-bulk-delete) with `--target-dataset`.
